### PR TITLE
Issue: Divide by zero on products

### LINKED ISSUE #15: Division by zero error on products
# CRITICAL ISSUE

When the client requests a single product, or all products, the status code is 500 and the response is always the following.

```
ZeroDivisionError at /products
division by zero
```

The most recent feature added by the team was adding an average rating key to each product. You might want to start there and see if there are any `try/catch` blocks you can implement.

### PR DESCRIPTION
**Pull request by nathanRomad**
If number is not zero.. then run code.
You can now GET (request) all products with no internal server error.

## Changes
- modified:   bangazonapi/models/product.py

## Requests / Responses
**Request**
GET `http://localhost:8000/products` - gets a new product

**Response**
HTTP/1.1 200 OK
```json
[
     {
        "id": 1,
        "name": "Optima",
        "price": 1655.15,
        "number_sold": 0,
        "description": "2008 Kia",
        "quantity": 3,
        "created_date": "2019-05-21",
        "location": "Onguday",
        "image_path": null,
        "average_rating": null
    },

```

## Testing
Open Postman
Select Bangazon Python API
Select Product directory
Select 'get all products'
Click 'run'
You should get back all 50 products with no internal server error 500.

You can also get back single (specific) products

## Related Issues

- Fixes #15

### CODE REVIEW

**Review by Scott47 — CHANGES_REQUESTED** [review]
This code works. However, the ticket asks for a try/catch, so please refactor as try block.

**Comment by nathanRomad** [comment]
I have replaced the 'if' statement with a try/catch block as requested.

**Review by Scott47 — COMMENTED** [review]
Did you know there is a `ZeroDivisionError` exception in python? Me, either until a couple of days ago. Change the except to look like what I have below and then consider this approved. Nice work. 
```
try:                            
    avg = total_rating / len(ratings)           
    return avg
except: ZeroDivisionError:  
    pass
   ```

**Comment by nathanRomad** [comment]
I made the changes you wanted to see sir!

**Review by Scott47 — APPROVED** [review]
👍

**Pull request merged**
